### ISSUE TITLE
shipit_static_analysis: AssertionError: sorry, but this version only supports 100 named groups

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#354]
When I run `./static_analysis_shared.sh d2758f635f72` to analyse [this revision](https://reviewboard-hg.mozilla.org/gecko/rev/d2758f635f72), I get the following error:

```
AssertionError: sorry, but this version only supports 100 named groups
Traceback (most recent call last):
  File "/nix/store/m59ypv529r20zhq0x33msq7ixr8ry4g8-clang-3.9.1/share/clang/run-clang-tidy.py", line 199, in <module>
    main()
  File "/nix/store/m59ypv529r20zhq0x33msq7ixr8ry4g8-clang-3.9.1/share/clang/run-clang-tidy.py", line 167, in main
    file_name_re = re.compile(\'(\' + \')|(\'.join(args.files) + \')\')
  File "/nix/store/4ka2jqn62q0nd9ilihihb2a12zp1ni7r-python-2.7.13/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
```

Full log:

```
cli_common.command: Command failed with code: 1 (command='run-clang-tidy.py -j 18 -p obj-x86_64-pc-linux-gnu/ -checks=-*,modernize-loop-convert,modernize-use-auto,modernize-use-default,modernize-raw-string-literal,modernize-use-bool-literals,modernize-use-override,modernize-use-nullptr js/public/CharacterEncoding.h js/public/Debug.h js/public/GCAPI.h js/public/HeapAPI.h js/public/RootingAPI.h js/src/builtin/AtomicsObject.cpp js/src/builtin/AtomicsObject.h js/src/builtin/DataViewObject.cpp js/src/builtin/Eval.cpp js/src/builtin/Intl.cpp js/src/builtin/MapObject.cpp js/src/builtin/ModuleObject.cpp js/src/builtin/ModuleObject.h js/src/builtin/Object.cpp js/src/builtin/Profilers.cpp js/src/builtin/Promise.cpp js/src/builtin/TestingFunctions.cpp js/src/builtin/TypedObject.cpp js/src/frontend/BytecodeCompiler.cpp js/src/frontend/BytecodeCompiler.h js/src/frontend/BytecodeEmitter.cpp js/src/frontend/BytecodeEmitter.h js/src/frontend/FoldConstants.cpp js/src/frontend/FoldConstants.h js/src/frontend/FullParseHandler.h js/src/frontend/NameCollections.h js/src/frontend/NameFunctions.cpp js/src/frontend/NameFunctions.h js/src/frontend/ParseNode.h js/src/frontend/Parser.cpp js/src/frontend/Parser.h js/src/frontend/SharedContext.h js/src/frontend/SyntaxParseHandler.h js/src/frontend/TokenStream.cpp js/src/frontend/TokenStream.h js/src/gc/Allocator.cpp js/src/gc/Allocator.h js/src/gc/AtomMarking.cpp js/src/gc/AtomMarking.h js/src/gc/Barrier.cpp js/src/gc/GCInternals.h js/src/gc/GCRuntime.h js/src/gc/Heap.h js/src/gc/Iteration.cpp js/src/gc/Marking.cpp js/src/gc/Marking.h js/src/gc/MemoryProfiler.cpp js/src/gc/Nursery-inl.h js/src/gc/Nursery.cpp js/src/gc/Nursery.h js/src/gc/RootMarking.cpp js/src/gc/Statistics.cpp js/src/gc/StoreBuffer.cpp js/src/gc/StoreBuffer.h js/src/gc/Verifier.cpp js/src/gc/Zone.cpp js/src/gc/Zone.h js/src/gdb/mozilla/unwind.py js/src/irregexp/NativeRegExpMacroAssembler.cpp js/src/irregexp/NativeRegExpMacroAssembler.h js/src/irregexp/RegExpEngine.cpp js/src/irregexp/RegExpInterpreter.cpp js/src/irregexp/RegExpStack.cpp js/src/irregexp/RegExpStack.h js/src/jit/Bailouts.cpp js/src/jit/BaselineBailouts.cpp js/src/jit/BaselineCacheIRCompiler.cpp js/src/jit/BaselineCompiler.cpp js/src/jit/BaselineDebugModeOSR.cpp js/src/jit/BaselineDebugModeOSR.h js/src/jit/BaselineFrame.cpp js/src/jit/BaselineIC.cpp js/src/jit/BaselineJIT.cpp js/src/jit/CacheIR.cpp js/src/jit/CacheIRCompiler.cpp js/src/jit/CodeGenerator.cpp js/src/jit/CompileWrappers.cpp js/src/jit/CompileWrappers.h js/src/jit/ExecutableAllocator.cpp js/src/jit/Ion.cpp js/src/jit/Ion.h js/src/jit/IonBuilder.cpp js/src/jit/IonBuilder.h js/src/jit/IonCacheIRCompiler.cpp js/src/jit/JitCompartment.h js/src/jit/JitFrames.cpp js/src/jit/JitcodeMap.cpp js/src/jit/Linker.cpp js/src/jit/MCallOptimize.cpp js/src/jit/MIR.cpp js/src/jit/MIR.h js/src/jit/MacroAssembler.cpp js/src/jit/MacroAssembler.h js/src/jit/SharedIC.cpp js/src/jit/SharedIC.h js/src/jit/VMFunctions.cpp js/src/jit/VMFunctions.h js/src/jit/arm/Assembler-arm.h js/src/jit/arm/Simulator-arm.cpp js/src/jit/arm/Simulator-arm.h js/src/jit/arm/Trampoline-arm.cpp js/src/jit/arm64/Assembler-arm64.cpp js/src/jit/arm64/Assembler-arm64.h js/src/jit/arm64/vixl/MozSimulator-vixl.cpp js/src/jit/arm64/vixl/Simulator-vixl.h js/src/jit/mips-shared/Assembler-mips-shared.h js/src/jit/mips32/Assembler-mips32.cpp js/src/jit/mips32/Simulator-mips32.cpp js/src/jit/mips32/Simulator-mips32.h js/src/jit/mips32/Trampoline-mips32.cpp js/src/jit/mips64/Assembler-mips64.cpp js/src/jit/mips64/Simulator-mips64.cpp js/src/jit/mips64/Simulator-mips64.h js/src/jit/mips64/Trampoline-mips64.cpp js/src/jit/none/MacroAssembler-none.h js/src/jit/shared/CodeGenerator-shared.cpp js/src/jit/x64/Assembler-x64.h js/src/jit/x64/Trampoline-x64.cpp js/src/jit/x86/Assembler-x86.h js/src/jit/x86/Trampoline-x86.cpp js/src/jsalloc.cpp js/src/jsalloc.h js/src/jsapi-tests/testAssemblerBuffer.cpp js/src/jsapi-tests/testFindSCCs.cpp js/src/jsapi-tests/testGCCellPtr.cpp js/src/jsapi-tests/testGCChunkPool.cpp js/src/jsapi-tests/testGCExactRooting.cpp js/src/jsapi-tests/testGCFinalizeCallback.cpp js/src/jsapi-tests/testGCGrayMarking.cpp js/src/jsapi-tests/testGCHeapPostBarriers.cpp js/src/jsapi-tests/testGCMarking.cpp js/src/jsapi-tests/testGCWeakRef.cpp js/src/jsapi-tests/testIsInsideNursery.cpp js/src/jsapi-tests/testJitMoveEmitterCycles.cpp js/src/jsapi-tests/testPreserveJitCode.cpp js/src/jsapi-tests/testProfileStrings.cpp js/src/jsapi-tests/testWeakMap.cpp js/src/jsapi.cpp js/src/jsapi.h js/src/jsarray.cpp js/src/jsarray.h js/src/jsatom.cpp js/src/jsatom.h js/src/jsatominlines.h js/src/jsbool.cpp js/src/jsbool.h js/src/jscntxt.cpp js/src/jscntxt.h js/src/jscntxtinlines.h js/src/jscompartment.cpp js/src/jscompartment.h js/src/jscompartmentinlines.h js/src/jsexn.cpp js/src/jsfriendapi.cpp js/src/jsfriendapi.h js/src/jsfun.cpp js/src/jsfun.h js/src/jsgc.cpp js/src/jsgc.h js/src/jsgcinlines.h js/src/jshashutil.h js/src/jsiter.cpp js/src/jsmath.cpp js/src/jsnum.cpp js/src/jsnum.h js/src/jsobj.cpp js/src/jsobj.h js/src/jsobjinlines.h js/src/jsopcode.cpp js/src/jspropertytree.cpp js/src/jspropertytree.h js/src/jspubtd.h js/src/jsscript.cpp js/src/jsscript.h js/src/jsstr.cpp js/src/jsstr.h js/src/jswatchpoint.cpp js/src/jsweakmap.cpp js/src/jsweakmap.h js/src/moz.build js/src/proxy/CrossCompartmentWrapper.cpp js/src/proxy/Proxy.cpp js/src/proxy/Wrapper.cpp js/src/shell/js.cpp js/src/vm/ArgumentsObject.cpp js/src/vm/ArrayBufferObject.cpp js/src/vm/ArrayObject-inl.h js/src/vm/ArrayObject.h js/src/vm/Caches.cpp js/src/vm/Caches.h js/src/vm/CharacterEncoding.cpp js/src/vm/CodeCoverage.cpp js/src/vm/Debugger-inl.h js/src/vm/Debugger.cpp js/src/vm/Debugger.h js/src/vm/DebuggerMemory.cpp js/src/vm/EnvironmentObject.cpp js/src/vm/EnvironmentObject.h js/src/vm/ErrorObject.cpp js/src/vm/ErrorObject.h js/src/vm/GeckoProfiler.cpp js/src/vm/GeneratorObject.h js/src/vm/GlobalObject.cpp js/src/vm/GlobalObject.h js/src/vm/HelperThreads.cpp js/src/vm/HelperThreads.h js/src/vm/Initialization.cpp js/src/vm/Interpreter-inl.h js/src/vm/Interpreter.cpp js/src/vm/MallocProvider.h js/src/vm/MemoryMetrics.cpp js/src/vm/MutexIDs.h js/src/vm/NativeObject-inl.h js/src/vm/NativeObject.cpp js/src/vm/NativeObject.h js/src/vm/ObjectGroup-inl.h js/src/vm/ObjectGroup.cpp js/src/vm/ObjectGroup.h js/src/vm/Printer.cpp js/src/vm/Printer.h js/src/vm/Probes-inl.h js/src/vm/Probes.h js/src/vm/ProxyObject.cpp js/src/vm/Realm.cpp js/src/vm/RegExpObject.cpp js/src/vm/RegExpObject.h js/src/vm/RegExpStatics.cpp js/src/vm/RegExpStatics.h js/src/vm/Runtime.cpp js/src/vm/Runtime.h js/src/vm/SavedStacks.cpp js/src/vm/Scope.cpp js/src/vm/Scope.h js/src/vm/SelfHosting.cpp js/src/vm/Shape-inl.h js/src/vm/Shape.cpp js/src/vm/Shape.h js/src/vm/Stack-inl.h js/src/vm/Stack.cpp js/src/vm/Stopwatch.cpp js/src/vm/String-inl.h js/src/vm/String.cpp js/src/vm/String.h js/src/vm/StringBuffer.cpp js/src/vm/StringBuffer.h js/src/vm/StringObject.h js/src/vm/StructuredClone.cpp js/src/vm/Symbol.cpp js/src/vm/Symbol.h js/src/vm/TraceLogging.cpp js/src/vm/TraceLogging.h js/src/vm/TypeInference-inl.h js/src/vm/TypeInference.cpp js/src/vm/TypeInference.h js/src/vm/TypedArrayObject.cpp js/src/vm/UbiNode.cpp js/src/vm/UnboxedObject-inl.h js/src/vm/UnboxedObject.cpp js/src/vm/UnboxedObject.h js/src/vm/Xdr.cpp js/src/vm/Xdr.h js/src/wasm/AsmJS.cpp js/src/wasm/AsmJS.h js/src/wasm/WasmCode.cpp js/src/wasm/WasmCompartment.cpp js/src/wasm/WasmCompile.cpp js/src/wasm/WasmCompile.h js/src/wasm/WasmInstance.cpp js/src/wasm/WasmInstance.h js/src/wasm/WasmJS.cpp js/src/wasm/WasmJS.h js/src/wasm/WasmSignalHandlers.cpp js/src/wasm/WasmSignalHandlers.h js/src/wasm/WasmTable.cpp js/src/wasm/WasmTypes.cpp js/src/wasm/WasmTypes.h js/src/gc/ZoneGroup.cpp js/src/gc/ZoneGroup.h js/src/threading/ProtectedData.cpp js/src/threading/ProtectedData.h' output=b'Enabled checks:\n    modernize-loop-convert\n    modernize-raw-string-literal\n    modernize-use-auto\n    modernize-use-bool-literals\n    modernize-use-default\n    modernize-use-nullptr\n    modernize-use-override\n\n\n' error=b'Traceback (most recent call last):\n  File "/nix/store/m59ypv529r20zhq0x33msq7ixr8ry4g8-clang-3.9.1/share/clang/run-clang-tidy.py", line 199, in <module>\n    main()\n  File "/nix/store/m59ypv529r20zhq0x33msq7ixr8ry4g8-clang-3.9.1/share/clang/run-clang-tidy.py", line 167, in main\n    file_name_re = re.compile(\'(\' + \')|(\'.join(args.files) + \')\')\n  File "/nix/store/4ka2jqn62q0nd9ilihihb2a12zp1ni7r-python-2.7.13/lib/python2.7/re.py", line 194, in compile\n    return _compile(pattern, flags)\n  File "/nix/store/4ka2jqn62q0nd9ilihihb2a12zp1ni7r-python-2.7.13/lib/python2.7/re.py", line 249, in _compile\n    p = sre_compile.compile(pattern, flags)\n  File "/nix/store/4ka2jqn62q0nd9ilihihb2a12zp1ni7r-python-2.7.13/lib/python2.7/sre_compile.py", line 583, in compile\n    "sorry, but this version only supports 100 named groups"\nAssertionError: sorry, but this version only supports 100 named groups\n')
Error: Command (`run-clang-tidy.py -j 18 -p obj-x86_64-pc-linux-gnu/ -checks=-*,modernize-loop-convert,modernize-use-auto,modernize-use-default,modernize-raw-string-literal,modernize-use-bool-literals,modernize-use-override,modernize-use-nullptr js/public/CharacterEncoding.h js/public/Debug.h js/public/GCAPI.h js/public/HeapAPI.h js/public/RootingAPI.h js/src/builtin/AtomicsObject.cpp js/src/builtin/AtomicsObject.h js/src/builtin/DataViewObject.cpp js/src/builtin/Eval.cpp js/src/builtin/Intl.cpp js/src/builtin/MapObject.cpp js/src/builtin/ModuleObject.cpp js/src/builtin/ModuleObject.h js/src/builtin/Object.cpp js/src/builtin/Profilers.cpp js/src/builtin/Promise.cpp js/src/builtin/TestingFunctions.cpp js/src/builtin/TypedObject.cpp js/src/frontend/BytecodeCompiler.cpp js/src/frontend/BytecodeCompiler.h js/src/frontend/BytecodeEmitter.cpp js/src/frontend/BytecodeEmitter.h js/src/frontend/FoldConstants.cpp js/src/frontend/FoldConstants.h js/src/frontend/FullParseHandler.h js/src/frontend/NameCollections.h js/src/frontend/NameFunctions.cpp js/src/frontend/NameFunctions.h js/src/frontend/ParseNode.h js/src/frontend/Parser.cpp js/src/frontend/Parser.h js/src/frontend/SharedContext.h js/src/frontend/SyntaxParseHandler.h js/src/frontend/TokenStream.cpp js/src/frontend/TokenStream.h js/src/gc/Allocator.cpp js/src/gc/Allocator.h js/src/gc/AtomMarking.cpp js/src/gc/AtomMarking.h js/src/gc/Barrier.cpp js/src/gc/GCInternals.h js/src/gc/GCRuntime.h js/src/gc/Heap.h js/src/gc/Iteration.cpp js/src/gc/Marking.cpp js/src/gc/Marking.h js/src/gc/MemoryProfiler.cpp js/src/gc/Nursery-inl.h js/src/gc/Nursery.cpp js/src/gc/Nursery.h js/src/gc/RootMarking.cpp js/src/gc/Statistics.cpp js/src/gc/StoreBuffer.cpp js/src/gc/StoreBuffer.h js/src/gc/Verifier.cpp js/src/gc/Zone.cpp js/src/gc/Zone.h js/src/gdb/mozilla/unwind.py js/src/irregexp/NativeRegExpMacroAssembler.cpp js/src/irregexp/NativeRegExpMacroAssembler.h js/src/irregexp/RegExpEngine.cpp js/src/irregexp/RegExpInterpreter.cpp js/src/irregexp/RegExpStack.cpp js/src/irregexp/RegExpStack.h js/src/jit/Bailouts.cpp js/src/jit/BaselineBailouts.cpp js/src/jit/BaselineCacheIRCompiler.cpp js/src/jit/BaselineCompiler.cpp js/src/jit/BaselineDebugModeOSR.cpp js/src/jit/BaselineDebugModeOSR.h js/src/jit/BaselineFrame.cpp js/src/jit/BaselineIC.cpp js/src/jit/BaselineJIT.cpp js/src/jit/CacheIR.cpp js/src/jit/CacheIRCompiler.cpp js/src/jit/CodeGenerator.cpp js/src/jit/CompileWrappers.cpp js/src/jit/CompileWrappers.h js/src/jit/ExecutableAllocator.cpp js/src/jit/Ion.cpp js/src/jit/Ion.h js/src/jit/IonBuilder.cpp js/src/jit/IonBuilder.h js/src/jit/IonCacheIRCompiler.cpp js/src/jit/JitCompartment.h js/src/jit/JitFrames.cpp js/src/jit/JitcodeMap.cpp js/src/jit/Linker.cpp js/src/jit/MCallOptimize.cpp js/src/jit/MIR.cpp js/src/jit/MIR.h js/src/jit/MacroAssembler.cpp js/src/jit/MacroAssembler.h js/src/jit/SharedIC.cpp js/src/jit/SharedIC.h js/src/jit/VMFunctions.cpp js/src/jit/VMFunctions.h js/src/jit/arm/Assembler-arm.h js/src/jit/arm/Simulator-arm.cpp js/src/jit/arm/Simulator-arm.h js/src/jit/arm/Trampoline-arm.cpp js/src/jit/arm64/Assembler-arm64.cpp js/src/jit/arm64/Assembler-arm64.h js/src/jit/arm64/vixl/MozSimulator-vixl.cpp js/src/jit/arm64/vixl/Simulator-vixl.h js/src/jit/mips-shared/Assembler-mips-shared.h js/src/jit/mips32/Assembler-mips32.cpp js/src/jit/mips32/Simulator-mips32.cpp js/src/jit/mips32/Simulator-mips32.h js/src/jit/mips32/Trampoline-mips32.cpp js/src/jit/mips64/Assembler-mips64.cpp js/src/jit/mips64/Simulator-mips64.cpp js/src/jit/mips64/Simulator-mips64.h js/src/jit/mips64/Trampoline-mips64.cpp js/src/jit/none/MacroAssembler-none.h js/src/jit/shared/CodeGenerator-shared.cpp js/src/jit/x64/Assembler-x64.h js/src/jit/x64/Trampoline-x64.cpp js/src/jit/x86/Assembler-x86.h js/src/jit/x86/Trampoline-x86.cpp js/src/jsalloc.cpp js/src/jsalloc.h js/src/jsapi-tests/testAssemblerBuffer.cpp js/src/jsapi-tests/testFindSCCs.cpp js/src/jsapi-tests/testGCCellPtr.cpp js/src/jsapi-tests/testGCChunkPool.cpp js/src/jsapi-tests/testGCExactRooting.cpp js/src/jsapi-tests/testGCFinalizeCallback.cpp js/src/jsapi-tests/testGCGrayMarking.cpp js/src/jsapi-tests/testGCHeapPostBarriers.cpp js/src/jsapi-tests/testGCMarking.cpp js/src/jsapi-tests/testGCWeakRef.cpp js/src/jsapi-tests/testIsInsideNursery.cpp js/src/jsapi-tests/testJitMoveEmitterCycles.cpp js/src/jsapi-tests/testPreserveJitCode.cpp js/src/jsapi-tests/testProfileStrings.cpp js/src/jsapi-tests/testWeakMap.cpp js/src/jsapi.cpp js/src/jsapi.h js/src/jsarray.cpp js/src/jsarray.h js/src/jsatom.cpp js/src/jsatom.h js/src/jsatominlines.h js/src/jsbool.cpp js/src/jsbool.h js/src/jscntxt.cpp js/src/jscntxt.h js/src/jscntxtinlines.h js/src/jscompartment.cpp js/src/jscompartment.h js/src/jscompartmentinlines.h js/src/jsexn.cpp js/src/jsfriendapi.cpp js/src/jsfriendapi.h js/src/jsfun.cpp js/src/jsfun.h js/src/jsgc.cpp js/src/jsgc.h js/src/jsgcinlines.h js/src/jshashutil.h js/src/jsiter.cpp js/src/jsmath.cpp js/src/jsnum.cpp js/src/jsnum.h js/src/jsobj.cpp js/src/jsobj.h js/src/jsobjinlines.h js/src/jsopcode.cpp js/src/jspropertytree.cpp js/src/jspropertytree.h js/src/jspubtd.h js/src/jsscript.cpp js/src/jsscript.h js/src/jsstr.cpp js/src/jsstr.h js/src/jswatchpoint.cpp js/src/jsweakmap.cpp js/src/jsweakmap.h js/src/moz.build js/src/proxy/CrossCompartmentWrapper.cpp js/src/proxy/Proxy.cpp js/src/proxy/Wrapper.cpp js/src/shell/js.cpp js/src/vm/ArgumentsObject.cpp js/src/vm/ArrayBufferObject.cpp js/src/vm/ArrayObject-inl.h js/src/vm/ArrayObject.h js/src/vm/Caches.cpp js/src/vm/Caches.h js/src/vm/CharacterEncoding.cpp js/src/vm/CodeCoverage.cpp js/src/vm/Debugger-inl.h js/src/vm/Debugger.cpp js/src/vm/Debugger.h js/src/vm/DebuggerMemory.cpp js/src/vm/EnvironmentObject.cpp js/src/vm/EnvironmentObject.h js/src/vm/ErrorObject.cpp js/src/vm/ErrorObject.h js/src/vm/GeckoProfiler.cpp js/src/vm/GeneratorObject.h js/src/vm/GlobalObject.cpp js/src/vm/GlobalObject.h js/src/vm/HelperThreads.cpp js/src/vm/HelperThreads.h js/src/vm/Initialization.cpp js/src/vm/Interpreter-inl.h js/src/vm/Interpreter.cpp js/src/vm/MallocProvider.h js/src/vm/MemoryMetrics.cpp js/src/vm/MutexIDs.h js/src/vm/NativeObject-inl.h js/src/vm/NativeObject.cpp js/src/vm/NativeObject.h js/src/vm/ObjectGroup-inl.h js/src/vm/ObjectGroup.cpp js/src/vm/ObjectGroup.h js/src/vm/Printer.cpp js/src/vm/Printer.h js/src/vm/Probes-inl.h js/src/vm/Probes.h js/src/vm/ProxyObject.cpp js/src/vm/Realm.cpp js/src/vm/RegExpObject.cpp js/src/vm/RegExpObject.h js/src/vm/RegExpStatics.cpp js/src/vm/RegExpStatics.h js/src/vm/Runtime.cpp js/src/vm/Runtime.h js/src/vm/SavedStacks.cpp js/src/vm/Scope.cpp js/src/vm/Scope.h js/src/vm/SelfHosting.cpp js/src/vm/Shape-inl.h js/src/vm/Shape.cpp js/src/vm/Shape.h js/src/vm/Stack-inl.h js/src/vm/Stack.cpp js/src/vm/Stopwatch.cpp js/src/vm/String-inl.h js/src/vm/String.cpp js/src/vm/String.h js/src/vm/StringBuffer.cpp js/src/vm/StringBuffer.h js/src/vm/StringObject.h js/src/vm/StructuredClone.cpp js/src/vm/Symbol.cpp js/src/vm/Symbol.h js/src/vm/TraceLogging.cpp js/src/vm/TraceLogging.h js/src/vm/TypeInference-inl.h js/src/vm/TypeInference.cpp js/src/vm/TypeInference.h js/src/vm/TypedArrayObject.cpp js/src/vm/UbiNode.cpp js/src/vm/UnboxedObject-inl.h js/src/vm/UnboxedObject.cpp js/src/vm/UnboxedObject.h js/src/vm/Xdr.cpp js/src/vm/Xdr.h js/src/wasm/AsmJS.cpp js/src/wasm/AsmJS.h js/src/wasm/WasmCode.cpp js/src/wasm/WasmCompartment.cpp js/src/wasm/WasmCompile.cpp js/src/wasm/WasmCompile.h js/src/wasm/WasmInstance.cpp js/src/wasm/WasmInstance.h js/src/wasm/WasmJS.cpp js/src/wasm/WasmJS.h js/src/wasm/WasmSignalHandlers.cpp js/src/wasm/WasmSignalHandlers.h js/src/wasm/WasmTable.cpp js/src/wasm/WasmTypes.cpp js/src/wasm/WasmTypes.h js/src/gc/ZoneGroup.cpp js/src/gc/ZoneGroup.h js/src/threading/ProtectedData.cpp js/src/threading/ProtectedData.h`) failed with code: 1.
```

It looks like `run-clang-tidy.py` (`clang-tidy-3.9`) doesn't support file lists that exceed 100 files.

**Comment by jankeromnes** [comment]
Note: @Sylvestre mentioned that he already reported this clang-tidy issue upstream, and that it was fixed by https://github.com/llvm-mirror/clang-tools-extra/commit/6da17244b6805ba4d8cef963a09d90d7ecb41f3b#diff-d084b68c49291b42fe7e4d5addb8f7b0

**Comment by garbas** [comment]
👍 awesome! a place where nix will shine :)

@jankeromnes should we use the revision you provided  (which might mean we would also bump the version) or we apply the patch on current version we are using?

also I found that ``clang/clang-tools`` packages used in ``src/shipit_static_analysis/default.nix`` are the of version 3.9 just by coincident and we should pin this down as well in ``nix/default.nix``.

If possible it would be nice to turn ``releng_pkgs`` into [nixpkgs overlay](http://nixos.org/nixpkgs/manual/#chap-overlays)

**Comment by jankeromnes** [comment]
I think we'll want to change the `clang-tidy` version used by this bot for two reasons:
- To include the upstream fix that supports > 100 files
- To include Mozilla-specific checkers (prefixed by `mozilla-`), e.g. by using a Mozilla-specific `clang-tidy` build (already generated on Treeherder by the `Clang-Tidy` task)

**Comment by La0** [comment]
The 100 files limitation is not present anymore, since i implemented the logic from `run-clang-tidy.py` directly into our codebase.

**Comment by jankeromnes** [comment]
Hooray! Thanks Bastien, I'll close this issue then.
