### ISSUE TITLE
shipit_code_coverage: Failure in updating marco-c/gecko-dev

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#481]
```
Traceback (most recent call last):
  File "/nix/store/h3zrrnc7xvhnl9g5cji2dhr95hd6j8bi-mozilla-shipit-code-coverage-1.0.0/bin/..shipit-code-coverage-wrapped-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/yw6b4yhc89dlgr8xib5apyswd8xzlvmr-python3.5-mozilla-cli-common-1.0.0/lib/python3.5/site-packages/cli_common/click.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/h3zrrnc7xvhnl9g5cji2dhr95hd6j8bi-mozilla-shipit-code-coverage-1.0.0/lib/python3.5/site-packages/shipit_code_coverage/cli.py", line 53, in main
    c.go()
  File "/nix/store/h3zrrnc7xvhnl9g5cji2dhr95hd6j8bi-mozilla-shipit-code-coverage-1.0.0/lib/python3.5/site-packages/shipit_code_coverage/codecov.py", line 208, in go
    self.update_github_repo()
  File "/nix/store/h3zrrnc7xvhnl9g5cji2dhr95hd6j8bi-mozilla-shipit-code-coverage-1.0.0/lib/python3.5/site-packages/shipit_code_coverage/codecov.py", line 80, in update_github_repo
    with open(os.path.expanduser('~/.ssh/id_rsa'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/.ssh/id_rsa'
```

**Comment by marco-c** [comment]
@garbas I need your expertise here

**Comment by marco-c** [comment]
Now it's failing with `FileNotFoundError: [Errno 2] No such file or directory: 'ssh-add'`. I guess `ssh-add` is not available in Nix by default.

**Comment by marco-c** [comment]
https://github.com/marco-c/mozilla-releng-services/tree/shipit_code_coverage_ssh_add is adding openssh and git to the docker image.

Now, the only thing missing is adding a user to nix (if I run `ssh`, I get an error like `no user exists for uid 0`).

**Comment by marco-c** [comment]
I'm going to disable updating the GitHub repo until we have fixed this issue (https://github.com/mozilla-releng/services/pull/487).
