### ISSUE TITLE
shipit_code_coverage and shipit_static_analysis are failing to import flask

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#540]
This is making code coverage tasks fail.

CC @garbas 

```
Traceback (most recent call last):
  File "/nix/store/2m2zd05515q4w0wfd36npa9vif63iv9v-mozilla-shipit-code-coverage-1.0.0/bin/..shipit-code-coverage-wrapped-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/xh8vd9x11hm3mzkfsimpk3mahfj5q8w7-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/j00hwdi1wfczhsankjij553zdd9hwl8d-python3.5-mozilla-cli-common-1.0.0/lib/python3.5/site-packages/cli_common/click.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/2m2zd05515q4w0wfd36npa9vif63iv9v-mozilla-shipit-code-coverage-1.0.0/lib/python3.5/site-packages/shipit_code_coverage/cli.py", line 44, in main
    MOZDEF=secrets.get('MOZDEF'),
  File "/nix/store/j00hwdi1wfczhsankjij553zdd9hwl8d-python3.5-mozilla-cli-common-1.0.0/lib/python3.5/site-packages/cli_common/log.py", line 157, in init_logger
    setup_sentry(project_name, channel, SENTRY_DSN)
  File "/nix/store/j00hwdi1wfczhsankjij553zdd9hwl8d-python3.5-mozilla-cli-common-1.0.0/lib/python3.5/site-packages/cli_common/log.py", line 102, in setup_sentry
    import raven.contrib.flask
  File "/nix/store/00b9hswj3x5cd4zf4a6d7cjv6mrvywph-python3.5-raven-6.1.0/lib/python3.5/site-packages/raven/contrib/flask.py", line 20, in <module>
    from flask import request, current_app, g
ImportError: No module named 'flask'
```

**Comment by marco-c** [comment]
All code coverage and static analysis tasks are currently failing.

**Comment by garbas** [comment]
this would be nice to catch in the tests

**Comment by garbas** [comment]
this would e hard to test since we would need to mock logging logic in sentry. #541 should fix this issue
