### ISSUE TITLE
Running apps is not working

### ISSUE THREAD

**Issue by armenzg** [mozilla-releng/services#577]
I got the same error with trying with ./please run releng-docs.
I'm on OSX.

armenzg@armenzg-mbp services$ ./please run shipit-frontend
 => Running shipit-frontend on https://0.0.0.0:8010 ...
Generating SSL Certificate
/nix/store/qvgv0sz3151243yhjapzjqjk4sgnw0kw-node-webpack-dev-server-2.6.1/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:396
		throw e;
		^

Error: EACCES: permission denied, open '/nix/store/qvgv0sz3151243yhjapzjqjk4sgnw0kw-node-webpack-dev-server-2.6.1/lib/node_modules/webpack-dev-server/ssl/server.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at new Server (/nix/store/qvgv0sz3151243yhjapzjqjk4sgnw0kw-node-webpack-dev-server-2.6.1/lib/node_modules/webpack-dev-server/lib/Server.js:394:7)
    at startDevServer (/nix/store/qvgv0sz3151243yhjapzjqjk4sgnw0kw-node-webpack-dev-server-2.6.1/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:389:12)
    at processOptions (/nix/store/qvgv0sz3151243yhjapzjqjk4sgnw0kw-node-webpack-dev-server-2.6.1/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:353:3)
    at Object.<anonymous> (/nix/store/qvgv0sz3151243yhjapzjqjk4sgnw0kw-node-webpack-dev-server-2.6.1/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:481:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by garbas** [comment]
Damn, i updated the dependencies (node) and didn't test if development mode works. This is the reason why I hate Node :) will prepare a fix

**Comment by armenzg** [comment]
Any updates on this?

I was trying to contribute to marco's project.

**Comment by garbas** [comment]
@armenzg I got the fix done, but forgot to merge it :( sorry. Will merge it asap
