### ISSUE TITLE
Run flake8 against all Python files

### ISSUE THREAD

**Issue by rail** [mozilla-releng/services#76]
I just tried to run a freshly created app and got an the following error:
```
Traceback (most recent call last):
  File "shipit/__init__.py", line 38, in <module>
    app.run(**app.get_run_options())
  File "/home/rail/work/mozilla/git/services/lib/releng_common/releng_common/__init__.py", line 84, in get_run_options
    debug=DEBUG,
NameError: name 'DEBUG' is not defined
```

It'd be great to run flake8 against all files. This would also improve PEP8 compatibility. ;)

**Comment by garbas** [comment]
oh .. i probably missed checking releng_common

**Comment by garbas** [comment]
looks like we dont run flake8 on anything ... fixing it here #77
